name: "wild"
description: "Use the Wild linker when building Rust code"
author: "Wild authors"

inputs:
  wild-version:
    description: "Wild version to use"
    required: false
    default: "0.5.0"

runs:
  using: "composite"
  steps:
    - run: |
        case "$RUNNER_ARCH" in
          X64)   target_arch="x86_64" ;;
          ARM64) target_arch="aarch64" ;;
          *) echo "Unsupported architecture: $RUNNER_ARCH" >&2; exit 1 ;;
        esac

        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/davidlattimore/wild/releases/download/${{ inputs.wild-version }}/wild-linker-installer.sh | sh

        mkdir -p "$HOME/.cargo"
        echo -e "# Added by wild GitHub Action\n[target.${target_arch}-unknown-linux-gnu]\nlinker = \"clang\"rustflags = [\"-Clink-arg=--ld-path=wild\"]\n" >>"$HOME/.cargo/config.toml"
      shell: bash
